name: infMinecraftHelloPlugin
version: '${project.version}'
main: cn.crtlprototypestudios.infminecrafthelloplugin.InfMinecraftHelloPlugin
api-version: 1.20

commands:
  tpa:
    description: Request to teleport to another player
    usage: /tpa <Player Username>
  tpaccept:
    description: Accept a teleport request
  tpdeny:
    description: Deny a teleport request
  spawn:
    description: Teleport to the world spawn point
  back:
    description: Return to your previous location before last teleport
  waypoint:
    description: Waypoint System

permissions:
  teleport.tpa:
    default: true
  teleport.spawn:
    default: true
  teleport.back:
    default: true
  teleport.waypoint:
    default: true
  teleport.waypoint.admin:
    default: op