name: infMinecraftHelloPlugin
version: '${project.version}'
main: cn.crtlprototypestudios.infminecrafthelloplugin.InfMinecraftHelloPlugin
api-version: 1.20

commands:
  tpa:
    description: Request to teleport to another player
    usage: /tpa <Player Username>
  tpaccept:
    description: Accept a teleport request
    usage: /tpaccept <Player Username>
  tpdeny:
    description: Deny a teleport request
    usage: /tpdeny <Player Username>
  spawn:
    description: Teleport to the world spawn point
    usage: /spawn
  back:
    description: Return to your previous location before last teleport
    usage: /back
  waypoint:
    description: Waypoint System
    usage: /waypoint <goto|add|remove|list|override> <Waypoint Name>

permissions:
  teleport.tpa:
    default: true
  teleport.spawn:
    default: true
  teleport.back:
    default: true
  teleport.waypoint:
    default: true